[phases.install]
cmds = [
  "NODE_ENV=development npm --prefix backend install",
  "NODE_ENV=development npm --prefix frontend install"
]

[phases.build]
cmds = ["NODE_ENV=development npm --prefix backend run build"]

[start]
cmd = "npm --prefix backend start"
