[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["NODE_ENV=development npm --prefix backend install"]

[phases.build]
cmds = ["NODE_ENV=development npm --prefix backend run build"]

[start]
cmd = "node backend/dist/server.js"
