export const C = {
  bg:           '#0A0F1E',
  bgSurface:    '#111827',
  bgCard:       '#1A2035',
  bgCardHover:  '#1E2845',
  border:       '#253050',
  borderLight:  '#1E2845',
  primary:      '#1C69D4',
  primaryHover: '#1557B8',
  accent:       '#4E9EFF',
  text:         '#F0F4FF',
  textMuted:    '#8B9CC8',
  textDim:      '#4A5880',
  success:      '#2ECC71',
  successBg:    'rgba(46,204,113,0.12)',
  warning:      '#F39C12',
  warningBg:    'rgba(243,156,18,0.12)',
  error:        '#E74C3C',
  errorBg:      'rgba(231,76,60,0.12)',
};

export const MILESTONES = [
  { key: 'PURCHASED',          en: 'Purchased',    de: 'Gekauft',       ar: 'تم الشراء',     icon: '🏭' },
  { key: 'INLAND_TO_PORT',     en: 'To Port',      de: 'Zum Hafen',     ar: 'إلى الميناء',   icon: '🚛' },
  { key: 'LOADING',            en: 'Loaded',       de: 'Verladen',      ar: 'محمّل',         icon: '⚓' },
  { key: 'OCEAN_TRANSIT',      en: 'Ocean',        de: 'Ozeanfahrt',    ar: 'عبر المحيط',    icon: '🚢' },
  { key: 'PORT_ARRIVAL',       en: 'Port Arrival', de: 'Hafeneinfahrt', ar: 'وصول الميناء',  icon: '🏖️' },
  { key: 'CUSTOMS',            en: 'Customs',      de: 'Zoll',          ar: 'الجمارك',       icon: '🛃' },
  { key: 'INLAND_TO_CUSTOMER', en: 'To Address',   de: 'Zur Adresse',   ar: 'إلى العنوان',   icon: '🚚' },
  { key: 'DELIVERED',          en: 'Delivered',    de: 'Geliefert',     ar: 'تم التسليم',    icon: '✅' },
];

export const ORDER_STATUS_COLOR = {
  PENDING:   'cv-badge-yellow',
  PAID:      'cv-badge-blue',
  SHIPPING:  'cv-badge-blue',
  DELIVERED: 'cv-badge-green',
};

export function calcFinalPrice(basePrice, shippingCost, taxRate, customsRate) {
  const duties = basePrice * (taxRate + customsRate);
  const profit = basePrice * 0.3;
  return Math.round(basePrice + shippingCost + duties + profit);
}

export const t = {
  en: {
    appName:        'BMW Export',
    catalogue:      'Catalogue',
    trackingTitle:  'Shipment Tracking',
    orderId:        'Order',
    login:          'Login',
    logout:         'Logout',
    email:          'Email',
    password:       'Password',
    signIn:         'Sign In',
    back:           '← Back',
    refresh:        'Refresh',
    loading:        'Loading…',
    noOrder:        'Order not found.',
    errorFetch:     'Failed to load data.',
    loginRequired:  'Please log in to continue.',
    vesselPosition: 'Vessel Position',
    lastUpdated:    'Last updated',
    autoRefresh:    'Auto-refreshing every 30 s',
    totalPrice:     'Total Price',
    status:         'Status',
    milestone:      'Current Milestone',
    billOfLading:   'Bill of Lading',
    vessel:         'Vessel',
    noEvents:       'No tracking events yet.',
    loginTitle:     'Sign in to your account',
    loginSubtitle:  'Track your car export shipment',
    registerTitle:  'Create an account',
    registerSubtitle: 'Browse and order cars from Germany',
    name:           'Full Name',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    register:       'Register',
    invalidCred:    'Invalid email or password.',
    yourOrders:     'Your Orders',
    noOrders:       'No orders yet.',
    trackShipment:  'Track Shipment',
    price:          'Price',
    model:          'Model',
    browseCatalogue: 'Browse Catalogue',
    allCars:        'All Cars',
    filterByMake:   'Filter by brand',
    newCars:        'New',
    usedCars:       'Used',
    allConditions:  'All',
    orderNow:       'Order This Car',
    orderSuccess:   'Order placed! Redirecting to tracking…',
    specs:          'Specifications',
    priceBreakdown: 'Price Breakdown',
    dealerPrice:    'Dealer price (Germany)',
    shipping:       'Shipping to Egypt',
    importDuties:   'Customs & import taxes',
    serviceFee:     'Import service fee',
    finalPrice:     'Final price (Egypt)',
    noListings:     'No cars available right now.',
    km:             'km',
    hp:             'hp',
    year:           'Year',
    fuel:           'Fuel',
    gearbox:        'Gearbox',
    mileage:        'Mileage',
    condition:      'Condition',
    power:          'Power',
    color:          'Exterior colour',
    bodyType:       'Body type',
    features:       'Key features',
    sourceLabel:    'Listed on',
  },
  de: {
    appName:        'BMW Export',
    catalogue:      'Katalog',
    trackingTitle:  'Sendungsverfolgung',
    orderId:        'Bestellung',
    login:          'Anmelden',
    logout:         'Abmelden',
    email:          'E-Mail',
    password:       'Passwort',
    signIn:         'Einloggen',
    back:           '← Zurück',
    refresh:        'Aktualisieren',
    loading:        'Lädt…',
    noOrder:        'Bestellung nicht gefunden.',
    errorFetch:     'Daten konnten nicht geladen werden.',
    loginRequired:  'Bitte anmelden.',
    vesselPosition: 'Schiffsposition',
    lastUpdated:    'Zuletzt aktualisiert',
    autoRefresh:    'Aktualisierung alle 30 s',
    totalPrice:     'Gesamtpreis',
    status:         'Status',
    milestone:      'Aktueller Meilenstein',
    billOfLading:   'Konnossement',
    vessel:         'Schiff',
    noEvents:       'Noch keine Ereignisse.',
    loginTitle:     'Melden Sie sich an',
    loginSubtitle:  'Verfolgen Sie Ihren Auto-Export',
    registerTitle:  'Konto erstellen',
    registerSubtitle: 'Autos aus Deutschland durchsuchen',
    name:           'Vollständiger Name',
    dontHaveAccount: 'Noch kein Konto?',
    alreadyHaveAccount: 'Bereits ein Konto?',
    register:       'Registrieren',
    invalidCred:    'Ungültige E-Mail oder Passwort.',
    yourOrders:     'Ihre Bestellungen',
    noOrders:       'Keine Bestellungen.',
    trackShipment:  'Sendung verfolgen',
    price:          'Preis',
    model:          'Modell',
    browseCatalogue: 'Katalog durchsuchen',
    allCars:        'Alle Autos',
    filterByMake:   'Nach Marke filtern',
    newCars:        'Neu',
    usedCars:       'Gebraucht',
    allConditions:  'Alle',
    orderNow:       'Jetzt bestellen',
    orderSuccess:   'Bestellung aufgegeben!',
    specs:          'Spezifikationen',
    priceBreakdown: 'Preisaufschlüsselung',
    dealerPrice:    'Händlerpreis (Deutschland)',
    shipping:       'Versand nach Ägypten',
    importDuties:   'Zoll & Importsteuern',
    serviceFee:     'Import-Servicegebühr',
    finalPrice:     'Endpreis (Ägypten)',
    noListings:     'Derzeit keine Autos verfügbar.',
    km:             'km',
    hp:             'PS',
    year:           'Jahr',
    fuel:           'Kraftstoff',
    gearbox:        'Getriebe',
    mileage:        'Kilometerstand',
    condition:      'Zustand',
    power:          'Leistung',
    color:          'Außenfarbe',
    bodyType:       'Karosserie',
    features:       'Ausstattung',
    sourceLabel:    'Inseriert auf',
  },
  ar: {
    appName:        'BMW تصدير',
    catalogue:      'الكتالوج',
    trackingTitle:  'تتبع الشحنة',
    orderId:        'الطلب',
    login:          'تسجيل الدخول',
    logout:         'تسجيل الخروج',
    email:          'البريد الإلكتروني',
    password:       'كلمة المرور',
    signIn:         'دخول',
    back:           'رجوع →',
    refresh:        'تحديث',
    loading:        '...جاري التحميل',
    noOrder:        'الطلب غير موجود.',
    errorFetch:     'فشل تحميل البيانات.',
    loginRequired:  'يرجى تسجيل الدخول.',
    vesselPosition: 'موقع السفينة',
    lastUpdated:    'آخر تحديث',
    autoRefresh:    'تحديث كل 30 ثانية',
    totalPrice:     'السعر الإجمالي',
    status:         'الحالة',
    milestone:      'المرحلة الحالية',
    billOfLading:   'بوليصة الشحن',
    vessel:         'السفينة',
    noEvents:       'لا توجد أحداث تتبع بعد.',
    loginTitle:     'تسجيل الدخول',
    loginSubtitle:  'تتبع شحنة سيارتك',
    registerTitle:  'إنشاء حساب',
    registerSubtitle: 'تصفح وطلب سيارات من ألمانيا',
    name:           'الاسم الكامل',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب؟',
    register:       'إنشاء حساب',
    invalidCred:    'بريد إلكتروني أو كلمة مرور غير صحيحة.',
    yourOrders:     'طلباتك',
    noOrders:       'لا توجد طلبات.',
    trackShipment:  'تتبع الشحنة',
    price:          'السعر',
    model:          'الموديل',
    browseCatalogue: 'تصفح الكتالوج',
    allCars:        'جميع السيارات',
    filterByMake:   'فلتر حسب الماركة',
    newCars:        'جديد',
    usedCars:       'مستعمل',
    allConditions:  'الكل',
    orderNow:       'اطلب الآن',
    orderSuccess:   'تم تقديم الطلب!',
    specs:          'المواصفات',
    priceBreakdown: 'تفاصيل السعر',
    dealerPrice:    'سعر الوكيل (ألمانيا)',
    shipping:       'الشحن إلى مصر',
    importDuties:   'الجمارك والضرائب',
    serviceFee:     'رسوم خدمة الاستيراد',
    finalPrice:     'السعر النهائي (مصر)',
    noListings:     'لا توجد سيارات متاحة حالياً.',
    km:             'كم',
    hp:             'حصان',
    year:           'السنة',
    fuel:           'الوقود',
    gearbox:        'ناقل الحركة',
    mileage:        'عداد المسافة',
    condition:      'الحالة',
    power:          'القدرة',
    color:          'اللون الخارجي',
    bodyType:       'نوع الهيكل',
    features:       'المميزات الرئيسية',
    sourceLabel:    'معروض على',
  },
};
