// Design tokens — import C for colours, t for translations, MILESTONES for stepper data
export const C = {
  bg:           '#0A0F1E',
  bgSurface:    '#111827',
  bgCard:       '#1A2035',
  bgCardHover:  '#1E2845',
  border:       '#253050',
  borderLight:  '#1E2845',
  primary:      '#1C69D4',
  primaryHover: '#1557B8',
  accent:       '#4E9EFF',
  text:         '#F0F4FF',
  textMuted:    '#8B9CC8',
  textDim:      '#4A5880',
  success:      '#2ECC71',
  successBg:    'rgba(46,204,113,0.12)',
  warning:      '#F39C12',
  warningBg:    'rgba(243,156,18,0.12)',
  error:        '#E74C3C',
  errorBg:      'rgba(231,76,60,0.12)',
};

export const MILESTONES = [
  { key: 'PURCHASED',          en: 'Purchased',    de: 'Gekauft',       ar: 'تم الشراء',     icon: '🏭' },
  { key: 'INLAND_TO_PORT',     en: 'To Port',      de: 'Zum Hafen',     ar: 'إلى الميناء',   icon: '🚛' },
  { key: 'LOADING',            en: 'Loaded',       de: 'Verladen',      ar: 'محمّل',         icon: '⚓' },
  { key: 'OCEAN_TRANSIT',      en: 'Ocean',        de: 'Ozeanfahrt',    ar: 'عبر المحيط',    icon: '🚢' },
  { key: 'PORT_ARRIVAL',       en: 'Port Arrival', de: 'Hafeneinfahrt', ar: 'وصول الميناء',  icon: '🏖️' },
  { key: 'CUSTOMS',            en: 'Customs',      de: 'Zoll',          ar: 'الجمارك',       icon: '🛃' },
  { key: 'INLAND_TO_CUSTOMER', en: 'To Address',   de: 'Zur Adresse',   ar: 'إلى العنوان',   icon: '🚚' },
  { key: 'DELIVERED',          en: 'Delivered',    de: 'Geliefert',     ar: 'تم التسليم',    icon: '✅' },
];

export const ORDER_STATUS_COLOR = {
  PENDING:   'cv-badge-yellow',
  PAID:      'cv-badge-blue',
  SHIPPING:  'cv-badge-blue',
  DELIVERED: 'cv-badge-green',
};

export const t = {
  en: {
    appName:        'BMW Export',
    trackingTitle:  'Shipment Tracking',
    orderId:        'Order',
    login:          'Login',
    logout:         'Logout',
    email:          'Email',
    password:       'Password',
    signIn:         'Sign In',
    back:           '← Back',
    refresh:        'Refresh',
    loading:        'Loading…',
    noOrder:        'Order not found.',
    errorFetch:     'Failed to load tracking data.',
    loginRequired:  'Please log in to track your shipment.',
    vesselPosition: 'Vessel Position',
    lastUpdated:    'Last updated',
    autoRefresh:    'Auto-refreshing every 30 s',
    configuration:  'Configuration',
    totalPrice:     'Total Price',
    status:         'Status',
    milestone:      'Current Milestone',
    billOfLading:   'Bill of Lading',
    vessel:         'Vessel',
    noEvents:       'No tracking events yet.',
    loginTitle:     'Sign in to your account',
    loginSubtitle:  'Track your BMW export shipment',
    registerTitle:  'Create an account',
    registerSubtitle: 'Start tracking your BMW export',
    name:           'Full Name',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    register:       'Register',
    invalidCred:    'Invalid email or password.',
    yourOrders:     'Your Orders',
    noOrders:       'No orders yet.',
    trackShipment:  'Track Shipment',
    price:          'Price',
    model:          'Model',
  },
  de: {
    appName:        'BMW Export',
    trackingTitle:  'Sendungsverfolgung',
    orderId:        'Bestellung',
    login:          'Anmelden',
    logout:         'Abmelden',
    email:          'E-Mail',
    password:       'Passwort',
    signIn:         'Einloggen',
    back:           '← Zurück',
    refresh:        'Aktualisieren',
    loading:        'Lädt…',
    noOrder:        'Bestellung nicht gefunden.',
    errorFetch:     'Daten konnten nicht geladen werden.',
    loginRequired:  'Bitte anmelden.',
    vesselPosition: 'Schiffsposition',
    lastUpdated:    'Zuletzt aktualisiert',
    autoRefresh:    'Aktualisierung alle 30 s',
    configuration:  'Konfiguration',
    totalPrice:     'Gesamtpreis',
    status:         'Status',
    milestone:      'Aktueller Meilenstein',
    billOfLading:   'Konnossement',
    vessel:         'Schiff',
    noEvents:       'Noch keine Ereignisse.',
    loginTitle:     'Melden Sie sich an',
    loginSubtitle:  'Verfolgen Sie Ihren BMW-Export',
    registerTitle:  'Konto erstellen',
    registerSubtitle: 'BMW-Export verfolgen',
    name:           'Vollständiger Name',
    dontHaveAccount: 'Noch kein Konto?',
    alreadyHaveAccount: 'Bereits ein Konto?',
    register:       'Registrieren',
    invalidCred:    'Ungültige E-Mail oder Passwort.',
    yourOrders:     'Ihre Bestellungen',
    noOrders:       'Keine Bestellungen.',
    trackShipment:  'Sendung verfolgen',
    price:          'Preis',
    model:          'Modell',
  },
  ar: {
    appName:        'BMW تصدير',
    trackingTitle:  'تتبع الشحنة',
    orderId:        'الطلب',
    login:          'تسجيل الدخول',
    logout:         'تسجيل الخروج',
    email:          'البريد الإلكتروني',
    password:       'كلمة المرور',
    signIn:         'دخول',
    back:           'رجوع →',
    refresh:        'تحديث',
    loading:        '...جاري التحميل',
    noOrder:        'الطلب غير موجود.',
    errorFetch:     'فشل تحميل البيانات.',
    loginRequired:  'يرجى تسجيل الدخول.',
    vesselPosition: 'موقع السفينة',
    lastUpdated:    'آخر تحديث',
    autoRefresh:    'تحديث كل 30 ثانية',
    configuration:  'المواصفات',
    totalPrice:     'السعر الإجمالي',
    status:         'الحالة',
    milestone:      'المرحلة الحالية',
    billOfLading:   'بوليصة الشحن',
    vessel:         'السفينة',
    noEvents:       'لا توجد أحداث تتبع بعد.',
    loginTitle:     'تسجيل الدخول',
    loginSubtitle:  'تتبع شحنة BMW الخاصة بك',
    registerTitle:  'إنشاء حساب',
    registerSubtitle: 'ابدأ في تتبع BMW',
    name:           'الاسم الكامل',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب؟',
    register:       'إنشاء حساب',
    invalidCred:    'بريد إلكتروني أو كلمة مرور غير صحيحة.',
    yourOrders:     'طلباتك',
    noOrders:       'لا توجد طلبات.',
    trackShipment:  'تتبع الشحنة',
    price:          'السعر',
    model:          'الموديل',
  },
};
